import type { Metadata } from "next";
import { Geist, Geist_Mono, Satisfy } from "next/font/google";
import "./globals.css";
import localFont from 'next/font/local';
import { ScrollProvider } from "@/components/providers/ScrollProvider";

const skyFont = localFont({
  src: [
    {
      path: '../public/font/regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../public/font/bold.woff2',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../public/font/ultrabold.woff2',
      weight: '800',
      style: 'normal',
    },
    {
      path: '../public/font/ultralight.woff2',
      weight: '200',
      style: 'normal',
    }
  ],
  variable: '--font-sky',
});

const satisfy = Satisfy({
  variable: "--font-satisfy",
  subsets: ["latin"],
  weight: ["400"]
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">


      <body
        className={`${geistSans.variable} ${geistMono.variable} ${skyFont.variable} ${satisfy.variable} antialiased`}
      >
        <ScrollProvider>
          {children}
        </ScrollProvider>
       
      </body>

    </html>
  );
}
